fix requirements with new h2ogpte version
h2oai/genai-app-store-apps pull request #39
Opened 2024-01-04 14:15 UTC by audreyleteve

Fix requirements as new version of h2ogpte server not compatible with requirements's client version

2024-01-05 00:18 UTC, mtanco requested changes
Thanks! But we need to keep the version pinned

2024-01-05 00:18 UTC, mtanco commented on CallCenterGPT/requirements.txt
> +h2ogpte
We should keep this pinned to the latest version of h2ogpte as we cannot confirm non-equal compatibility

2024-01-05 20:35 UTC, mtanco approved these changes

2024-01-05 20:36 UTC, merged

2024-01-08 08:10 UTC, audreyleteve commented on CallCenterGPT/requirements.txt
> +h2ogpte
thank you for the change @mtanco !